#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/docopt/docopt/src/docopt.php';

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: stylish]
DOC;

$arguments = Docopt::handle($doc, ['version' => 'gendiff 1.0']);

$firstFile = $arguments['<firstFile>'];
$secondFile = $arguments['<secondFile>'];

$firstData = file_get_contents($firstFile);
$secondData = file_get_contents($secondFile);

$data1 = json_decode($firstData);
$data2 = json_decode($secondData);

echo "First file data:\n";
print_r($data1);

echo "\nSecond file data:\n";
print_r($data2);