name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: php-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Shangrion_php-project-48
            -Dsonar.organization=shangrion
            -Dsonar.php.coverage.reportPaths=build/coverage/clover.xml
            -Dsonar.php.tests.reportPath=build/test-results/phpunit.xml
            -Dsonar.coverage.exclusions=tests/**